# =============================================================================
# File        : deno.yml
# Author      : yukimemi
# Last Change : 2025/10/04 20:37:40.
# =============================================================================

name: deno

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    name: Publish to JSR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno publish

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        if: matrix.os == 'ubuntu-latest'
        id: vim-rhysd
        with:
          version: "v9.2.0148" # renovate: datasource=github-releases depName=vim/vim-win32-installer

      - uses: thinca/action-setup-vim@v3
        if: matrix.os != 'ubuntu-latest'
        id: vim-thinca
        with:
          vim_type: "Vim"
          vim_version: "v9.2.0148" # renovate: datasource=github-releases depName=vim/vim-win32-installer

      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "v0.11.6" # renovate: datasource=github-releases depName=neovim/neovim

      - uses: denoland/setup-deno@v2

      - run: deno task ci
        env:
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim-rhysd.outputs.executable || steps.vim-thinca.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
